[build]
  command = "cd pepl-backend && npm install && npm run build && cd ../pepl-frontend && npm install && npm run build"
  publish = "pepl-frontend/.next"

[functions]
  directory = "pepl-backend/dist"
  node_bundler = "esbuild"
  included_files = ["pepl-backend/dist/**/*.js"]
  external_node_modules = ["@nestjs/microservices", "@nestjs/websockets", "cache-manager"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
